# Generated by Django 3.0.10 on 2021-01-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getAnswers', '0003_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='response',
        ),
        migrations.AddField(
            model_name='provider',
            name='auth_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
